name: example
version: 1.0.0
environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  liquid_swipe:
    path: ..\
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
